// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnfhzaxdlcjrvhcgodev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuZmh6YXhkbGNqcnZoY2dvZGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Mjk4MTIsImV4cCI6MjA2OTIwNTgxMn0.wT1cWHqKZkd6dipLRI_CO4BQanBUtrFK4ha4rRPk6YM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});